name: Build with xmake on windows
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.1'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          modules: 'qtmultimedia'

      - uses: jmarrec/setup-qtifw@v1
        with:
          qtifw-version: '4.x'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build
        run: |
          xmake config --yes
          xmake build --jobs=2

      - name: Copy Files 
        shell: pwsh
        run: |
          mkdir ./packaging/org.midieditor.midieditor/data/
          cp ./bin/ProMidEdit.exe ./packaging/org.midieditor.midieditor/data/ProMidEdit.exe
          windeployqt ./packaging/org.midieditor.midieditor/data/ProMidEdit.exe
          mkdir ./packaging/org.midieditor.midieditor/data/metronome
          cp ./run_environment/metronome/metronome-01.wav ./packaging/org.midieditor.midieditor/data/metronome
          mkdir ./packaging/org.midieditor.manual/data/
          cp -Recurse -Path ./manual/ -Destination ./packaging/org.midieditor.manual/data/

      - name: Packaging
        shell: cmd
        run: |
          binarycreator.exe --offline-only -c .\scripts\packaging\windows\config.xml -p .\packaging Install.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ProMidEdit-Installer
          path: Install.exe